# This is a utility file to test the mission-control docker image locally
# docker-compose --env-file=.env.docker-compose up

version: "3.9"
services:
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "80:80"
  showit:
    env_file:
      - .env.docker-compose
    build:
      context: .
      args:
        PUBLIC_PATH: /prohlížíme
        REACT_APP_SPARQL_ENDPOINT: https://xn--slovnk-7va.gov.cz/prohlizime/sluzby/db-server/repositories/termit
